Sprint 1
itwassoclear/middle.messenger.praktikum.yandex pull request #1
Opened 2022-11-07 17:48 UTC by itwassoclear

2022-11-07 18:27 UTC, podlovchenko requested changes
Привет, по заданию проект необходимо запускать на 3000 порту, было бы отлично добавить команду start в package.json и почистить зависимости

2022-11-07 18:27 UTC, podlovchenko commented on package.json
> +    "build": "parcel build ./index.hbs"
Нет команды для запуска сервера на express

2022-11-07 18:27 UTC, podlovchenko commented on package.json
> +    "@anikin/parcel-transformer-handlebars": "^1.0.9",
Лучше задавать фиксированные версии зависимостям. Если однажды решишь, удалить package-lock.json файл и попытаться повторно установить зависимости с помощью команды npm install, npm установит последние версии зависимостей, что может привести к ошибкам

2022-11-07 18:27 UTC, podlovchenko commented on package.json
> +    "hbs": "^4.2.0"
В devDependencies указывается то, что необходимо для сборки и разработки приложения, в dependencies то, что необходимо непосредственно для работу приложения (express)

2022-11-07 18:27 UTC, podlovchenko commented on package.json
> +    "stream-http": "^3.2.0",
Точно все эти зависимости нужны?

2022-11-07 18:27 UTC, podlovchenko commented on server.js
> +const PORT = 1312;
Часто требуется возможность получить порт снаружи скрипта, не изменяя код, это можно сделать через переменное окружение:
process.env.PORT || PORT;
https://nodejs.org/dist/latest-v8.x/docs/api/process.html

2022-11-07 18:27 UTC, podlovchenko commented on server.js
> +const PORT = 1312;
Работать должно на 3000 порту по заданию

2022-11-07 18:27 UTC, podlovchenko commented on src/modules/sum.js
> +// }
Закомментированный код лучше не оставлять в проекте

2022-11-07 19:36 UTC, itwassoclear commented on package.json
> +    "build": "parcel build ./index.hbs"
привет!
и в теории и в чек листе написано, что проект должен запускаться на 3000 порту, но не сказано какая сборка. 
для dev сборки есть требования к порту? parcel по умолчанию хочет занять порт 1234 - это ок? на 3000 должна только продакшн сборка запускаться?

2022-11-07 19:36 UTC, itwassoclear commented on package.json
> +    "stream-http": "^3.2.0",
большая часть зависимостей затягивается при запуске сборки парселом. но я почистила

2022-11-08 11:40 UTC, podlovchenko commented on package.json
> +    "start": "parcel build ./index.hbs && node ./server.js"
Можно переиспользовать команды
```suggestion
    "start": "npm run build && node ./server.js"
```

2022-11-08 11:40 UTC, podlovchenko commented on package.json
> +    "dev": "parcel ./index.hbs --no-cache",
Можно было оставить как было с ключом --port 3000

2022-11-08 11:40 UTC, podlovchenko commented on server.js
> +
Сейчас при запуске приложения локально через npm run start можно получить страницу только запрашивая напрямую index.html
Стоит добавить
```suggestion
app.use('*', (_req, res) => {
  res.sendFile(path.join(__dirname, 'dist/index.html'));
});
```

2022-11-08 11:40 UTC, podlovchenko commented
Работу принимаю)

2022-11-08 14:47 UTC, merged